FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1.6-runtime-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./
CMD ["dotnet", "iotedgeSQLite.dll"]